In [2]:
print "Parsing"

Parsing


In [5]:
f = open('DOR_GLAS.txt');

In [6]:
print f

<open file 'DOR_GLAS.txt', mode 'r' at 0x7fa1380c4f60>


In [7]:
data = f.readlines()

In [8]:
print data

['#ResBW\tResN\tResBW\tResN\tMinDist\n', '1.57\tI74\t2.44\tF89\t4.5\n', '2.42\tY87\t2.44\tM142\t2.9\n', '2.47\tA92\t1.53\tV70\t3.8\n', '2.47    A92\t1.50\tN67\t3.6\n', '1.50\tN67\t2.50\tD95\t3.4\n', '2.50\tD95\t7.46\tS311\t2.7\n', '1.50\tN67\t7.46\tS311\t2.9\n', '3.34\tY130\t4.57\tG180\t3.6\n', '4.53\tA176\t3.34\tY130\t3.9\n', '4.53\tA176\t3.38\tT134\t3.7\n', '3.38\tT134\t4.50\tW173\t3.9\n', '3.44\tT140\t5.54\tI229\t3.7\n', '5.54\tI229\t6.41\tV267\t3.5\n', '3.47\tS143\t5.57\tC232\t4.3\n', '5.57\tC232\t3.51\tY147\t4.0\n', '3.51\tY147\t5.60\tL235\t3.8\n', '2.43\tI88\t7.53\tY318\t4.0\n', '3.36\tM132\t6.48\tW274\t4.0\n', '3.40\tI136\t6.44\tF270\t3.8\n', '1.46\tG63\t7.47\tS312\t3.7\n', '1.49\tG66\t7.50\tP315\t3.8\n', '6.51\tI277\t7.39\tA305\t6.6\n', '6.51\tI277\t7.38\tI304\t3.6\n', '6.47\tC273\t7.35\tN310\t3.8\n']


In [9]:
for line in data:
    key, value = line.split("\t")

ValueError: too many values to unpack

In [10]:
import csv

In [11]:
csv.reader()

TypeError:  expected at least 1 arguments, got 0

In [15]:
f1 = csv.reader(StringIO.StringIO("DOR_GLAS.txt"), delimiter='\t')

In [13]:
import StringIO

In [16]:
print f1

In [18]:
for row in f1:
    print row[f1]

In [20]:
f2 = csv.reader(open("DOR_GLAS.txt"), delimiter='\t')

In [30]:
print f2

In [34]:
for row in f2:
    r=row.strip()
    if not r.startswith("#"):
        print r
        

In [33]:
import sys

In [35]:
print r

NameError: name 'r' is not defined

In [36]:
print row

['6.47', 'C273', '7.35', 'N310', '3.8']


In [40]:
for row in f2:
    print row

In [1]:
print "Looping over parsed variables"

Looping over parsed variables


In [2]:
import csv

In [3]:
f = csv.reader(open('DOR_GLAS.csv'))

In [4]:
import numpy as nm

In [5]:
ContactsArray = nm.zeros((24,2))

In [6]:
for i,row in enumerate(f):
    ContactsArray[i]=[row[0], row[1]]

In [7]:
ContactsArray

array([[  74.,   89.],
       [  87.,  142.],
       [  92.,   70.],
       [  92.,   67.],
       [  67.,   95.],
       [  95.,  311.],
       [  67.,  311.],
       [ 130.,  180.],
       [ 176.,  130.],
       [ 176.,  134.],
       [ 134.,  173.],
       [ 140.,  229.],
       [ 229.,  267.],
       [ 143.,  232.],
       [ 232.,  147.],
       [ 147.,  235.],
       [  88.,  318.],
       [ 132.,  274.],
       [ 136.,  270.],
       [  63.,  312.],
       [  66.,  315.],
       [ 277.,  305.],
       [ 277.,  304.],
       [ 273.,  310.]])

In [8]:
for row in ContactsArray:
    print row

[ 74.  89.]
[  87.  142.]
[ 92.  70.]
[ 92.  67.]
[ 67.  95.]
[  95.  311.]
[  67.  311.]
[ 130.  180.]
[ 176.  130.]
[ 176.  134.]
[ 134.  173.]
[ 140.  229.]
[ 229.  267.]
[ 143.  232.]
[ 232.  147.]
[ 147.  235.]
[  88.  318.]
[ 132.  274.]
[ 136.  270.]
[  63.  312.]
[  66.  315.]
[ 277.  305.]
[ 277.  304.]
[ 273.  310.]


In [9]:
from MDAnalysis import Universe as u

In [10]:
topol = u('4N6H.pdb')

In [11]:
from MDAnalysis.analysis import distances as dists

In [17]:
print "%d" % 1

1


In [22]:
for row in ContactsArray:
    print "%d, %d" % (row[0], row[1])

74, 89
87, 142
92, 70
92, 67
67, 95
95, 311
67, 311
130, 180
176, 130
176, 134
134, 173
140, 229
229, 267
143, 232
232, 147
147, 235
88, 318
132, 274
136, 270
63, 312
66, 315
277, 305
277, 304
273, 310


In [49]:
resid1 = str("resid %d") %74
resid2 = str("resid %d") %89
ContactArray = dists.distance_array(topol.select_atoms(resid1).get_positions(), topol.select_atoms(resid2).get_positions())
ContactArray

array([[  8.01501416,   7.60614444,   8.94647989,   9.17213875,
          7.10779245,   6.94500261,   8.17743188,   5.79783425,
          8.42329523,   6.14576513,   7.50386324],
       [  7.49746379,   7.18053985,   8.58753197,   8.98480982,
          6.48382268,   6.44820313,   7.71929406,   5.41529165,
          8.08888202,   5.92816939,   7.28759928],
       [  8.35075973,   7.8854732 ,   9.20127332,   9.57838838,
          6.94363344,   6.68545317,   7.82130644,   5.5784075 ,
          8.01957662,   5.83230632,   7.11743986],
       [  8.95968706,   8.60060507,   9.93704112,  10.41952258,
          7.5519796 ,   7.3892967 ,   8.49872801,   6.39838401,
          8.74560816,   6.69540866,   7.91852506],
       [  5.95480155,   5.66918154,   7.10833003,   7.58672584,
          5.0020102 ,   5.13141863,   6.4672239 ,   4.26786926,
          7.01501177,   5.06677033,   6.40561587],
       [  5.48200001,   5.48672701,   6.99145502,   7.50810108,
          5.20598396,   5.64761993,   7.0

In [51]:
print "Get minimum value"

Get minimum value


In [52]:
ContactArray

array([[  8.01501416,   7.60614444,   8.94647989,   9.17213875,
          7.10779245,   6.94500261,   8.17743188,   5.79783425,
          8.42329523,   6.14576513,   7.50386324],
       [  7.49746379,   7.18053985,   8.58753197,   8.98480982,
          6.48382268,   6.44820313,   7.71929406,   5.41529165,
          8.08888202,   5.92816939,   7.28759928],
       [  8.35075973,   7.8854732 ,   9.20127332,   9.57838838,
          6.94363344,   6.68545317,   7.82130644,   5.5784075 ,
          8.01957662,   5.83230632,   7.11743986],
       [  8.95968706,   8.60060507,   9.93704112,  10.41952258,
          7.5519796 ,   7.3892967 ,   8.49872801,   6.39838401,
          8.74560816,   6.69540866,   7.91852506],
       [  5.95480155,   5.66918154,   7.10833003,   7.58672584,
          5.0020102 ,   5.13141863,   6.4672239 ,   4.26786926,
          7.01501177,   5.06677033,   6.40561587],
       [  5.48200001,   5.48672701,   6.99145502,   7.50810108,
          5.20598396,   5.64761993,   7.0

In [53]:
nm.amin(ContactArray)

4.0436495572668223

In [73]:
minDistArray = []
for row in ContactsArray:
    resid1 = str("resid %d") % row[0];
    resid2 = str("resid %d") % row[1];
    coords1 = topol.select_atoms(resid1).get_positions()
    coords2 = topol.select_atoms(resid2).get_positions()
    ContactsMatrix = dists.distance_array(coords1, coords2)
    minDistArray.append(nm.amin(ContactsMatrix))
    ContactsMatrix = 0

In [75]:
minDistArray

[4.0436495572668223,
 2.9313487254907149,
 3.81199418109665,
 3.5000023407424741,
 3.4461192106658838,
 2.7407641410880315,
 2.9238423456953471,
 3.6234785596521535,
 3.8772473266213607,
 3.6647524671403158,
 3.8669760592494571,
 3.682638314275728,
 3.5088267368419532,
 4.1074842875297817,
 4.0412913600263511,
 3.6547541990048189,
 3.6292905965536613,
 3.6753364775629511,
 3.7517300501312918,
 3.6886843410922854,
 3.8360257269058762,
 6.6384744005889393,
 3.6431711107727947,
 3.6338791466196807]

In [80]:
GLAS = 0
for dist in minDistArray:
    if dist < 4:
        GLAS += 1

In [81]:
GLAS

20

In [1]:
run ../../scripts/pyGLAS.py -r 4N6H_GPCRDB.pdb


Checking configuration input...

Since you didn't input any CHICOs or NACHOs, I will attempt to calculate them from the input structure.
This may not be the most accurate way to do this, so please be careful when using the results.


Successfully loaded topology.

Attempting to get CHICOs from input file...

Since you asked me to find the CHICOs, I will write them to a file so you can verify and confirm them.
If any are wrong, please change them and re-run me using the flag --chicos followed by the CHICOs file.
Thank you.

CHICOs loaded from input structure.

Attempting to get NACHOs from input file...

Since you asked me to find the NACHOs, I will write them to a file so you can verify and confirm them.
If any are wrong, please change them and re-run me using the flag --chicos followed by the NACHOs file.
Thank you.

NACHOs loaded from input structure.

Pre-initialising relevant variables and arrays...



/biggin/b15/shil4362/scripts/anaconda2/lib/python2.7/site-packages/numpy/lib/utils.py:99: DeprecationWarning: `get_positions` is deprecated!
This will be removed in version 0.16.0; use `positions` property instead
  warnings.warn(depdoc, DeprecationWarning)


Pre-initialising relevant variables and arrays...



In [2]:
minDistDict

{}

In [3]:
system

<Universe with 3582 atoms>

In [4]:
SAS = 0

In [5]:
minDistDict = {}

In [13]:
for key in nachosDict:
    resid1 = str("resid %s and not name H*") % nachosDict[key][0];
    resid2 = str("resid %s and not name H*") % nachosDict[key][1];
    coords1 = system.select_atoms(resid1).get_positions();
    coords2 = system.select_atoms(resid2).get_positions();
    ContactsMatrix = dists.distance_array(coords1, coords2)
    minDistDict[key] = nm.amin(ContactsMatrix)
    ContactsMatrix = 0
    
if minDistDict is not None:
    for key in minDistDict:
        if key < 8:
            if minDistDict[key] < args.cutoff:
                SAS -= 1;
        elif key > 7:
            if minDistDict[key] < args.cutoff:
                SAS += 1;
                
print SAS

-4
